### ISSUE TITLE
Chapter08 - how code added about extract downloaded imdb.tgz

### ISSUE THREAD

**Issue by hygjob** [PacktPublishing/Natural-Language-Processing-with-Python-Quick-Start-Guide#1]
Thank you for your effort for introduction for NLP.
I learned about many basic NLP knowledge from this book. 

When I execute chapter08 code I got error about training data of imdb.tgz.
Later, I found the error I should extract downloaded imdb.tag my self. 
So I suggest the extract code added for downloaded file.

For example.

[file] model_train.py

#data download
if not data_path.exists():
    data_url = "http://files.fast.ai/data/aclImdb.tgz"
    get_data(data_url, "data/imdb.tgz")    
    #below is my suggested code - for extract the downloaded file  
    import tarfile    
    tar = tarfile.open("./data/imdb.tgz", "r:gz")    
    tar.extractall(path="./data")    
    tar.close()

Sorry. I can't do the indentation well . 
But I believe you understand my intention.

all code is in scope of "if not data_path.exists()"

**Comment by NirantK** [comment]
Did you mean something like this? 
```python
import tarfile
from pathlib import Path

if not data_path.exists():
	data_url = "http://files.fast.ai/data/aclImdb.tgz"
	filename = Path("./data") / data_url.split("/")[-1]
	get_data(data_url, filename)
	tar = tarfile.open(filename, "r:gz")
	tar.extractall(path="./data")
	tar.close()
```

**Comment by hygjob** [comment]
Yes, that's what I mean.

**Comment by NirantK** [comment]
Got it, thanks a ton @hygjob
