### ISSUE TITLE
Chapter 6 errors in code

### ISSUE THREAD

**Issue by ajitbalakrishnan** [PacktPublishing/Natural-Language-Processing-with-Python-Quick-Start-Guide#2]
Your book and Github says
val_df = pd.read_csv("data/valid.csv")
...but there no valid.csv on the Kaggle link you provide:
https://www.kaggle.com/c/jigsaw-toxic-comment-classification-challenge/data

Second issue:
train_df = pd.read_csv("data/train.csv")
...shows a file not found error...why are you showing this?

**Comment by NirantK** [comment]
Hey @ajitbalakrishnan, please create a valid split from the Jigsaw data?

I am guessing that the FileNotFoundError got left in as a typo. Will fix it in next round of upgrades.
